import React from 'react';
import InteractiveBlock from '../shared/InteractiveBlock';

export default function T09_NASNetView() {
  return (
    <div className="space-y-8 animate-fadeIn">
      <h2 className="text-3xl font-extrabold text-gray-900 border-b-2 border-gray-200 pb-2">
        T-09: NASNet (Neural Architecture Search Network)
      </h2>

      {/* Section 1 */}
      <section>
        <h3 className="text-2xl font-bold text-blue-800 mb-3">1. Motivation and Context</h3>
        <p className="text-gray-700 leading-relaxed mb-4">
          Historically, designing a state-of-the-art neural network required teams of PhD researchers relying heavily on human intuition, trial-and-error, and years of experience. This manual "feature engineering" of network topologies was becoming a massive bottleneck. Researchers at Google Brain asked: <em>Can we automate the design process itself?</em> NASNet was motivated by the desire to use reinforcement learning to let an AI design the optimal CNN architecture, removing human bias from the equation.
        </p>
      </section>

      <hr className="border-gray-300" />

      {/* Section 2 */}
      <section>
        <h3 className="text-2xl font-bold text-blue-800 mb-3">2. Architecture Design</h3>
        <p className="text-gray-700 leading-relaxed mb-4">
          The core innovation of NASNet isn't a specific convolution type, but rather the <strong>Search Space Strategy</strong>. Searching for a massive ImageNet architecture from scratch was computationally impossible. Instead, the Recurrent Neural Network (RNN) controller was tasked with finding two small, optimal "Cells" on a much smaller dataset (CIFAR-10):
          <br /><br />
          1. <strong>Normal Cell:</strong> Returns a feature map of the same dimension as its input.<br />
          2. <strong>Reduction Cell:</strong> Returns a feature map where the height and width are reduced by a factor of two.
          <br /><br />
          Once these highly complex, unintuitive, machine-generated cells were discovered, they were simply stacked together as many times as necessary to scale up to the massive ImageNet dataset.
        </p>
        
        {/* Simulating an AutoML Reduction Cell */}
        <InteractiveBlock 
          title="Machine-Designed Reduction Cell (Downsampling)" 
          defaultW={32} 
          defaultCin={128} 
          defaultK={5} 
          defaultS={2} 
          defaultP={2} 
          defaultCout={256} 
        />
        <p className="text-sm text-gray-500 italic mt-2">
          * Notice the stride (S=2). This specific block represents the Reduction Cell stepping down the spatial resolution (W<sub>out</sub> = 16) while expanding the feature space (C<sub>out</sub> = 256), a topology specifically chosen by the Reinforcement Learning controller to maximize accuracy!
        </p>
      </section>

      <hr className="border-gray-300" />

      {/* Section 3 */}
      <section>
        <h3 className="text-2xl font-bold text-blue-800 mb-3">3. Experimental Results and Impact</h3>
        <ul className="list-disc pl-6 text-gray-700 space-y-2">
          <li><strong>Surpassing Human Design:</strong> NASNet-A achieved an 82.7% top-1 accuracy on ImageNet, outperforming all manually designed human architectures at the time (like Inception-ResNet-v2).</li>
          <li><strong>Transferability:</strong> The architecture proved that cells learned on a small dataset (CIFAR-10) could successfully transfer and scale to much larger, more complex datasets (ImageNet).</li>
          <li><strong>Birth of AutoML:</strong> This paper kickstarted the modern AutoML revolution, leading directly to the development of highly optimized architectures like EfficientNet (which used a similar search strategy).</li>
        </ul>
      </section>

      <hr className="border-gray-300" />

      {/* Section 4 */}
      <section>
        <h3 className="text-2xl font-bold text-blue-800 mb-3">4. Conclusion and Critical Reflection</h3>
        <p className="text-gray-700 leading-relaxed mb-4">
          NASNet represents a fundamental paradigm shift in deep learning. However, its primary limitation is the astronomical computational cost of the search process itself. Finding the NASNet cells required 450 GPUs running for 4 days straight (over 40,000 GPU-hours). Furthermore, because the architecture is generated by a machine, the resulting cell topologies look chaotic and fragmented, making them highly unintuitive for researchers to analyze or debug compared to the clean geometry of a ResNet.
        </p>
      </section>

      {/* References */}
      <section className="bg-gray-100 p-6 rounded-lg mt-8">
        <h3 className="text-xl font-bold text-gray-800 mb-3">References</h3>
        <ul className="list-decimal pl-6 text-sm text-gray-600 space-y-1">
          <li>Zoph, B., Vasudevan, V., Shlens, J., & Le, Q. V. (2018). Learning Transferable Architectures for Scalable Image Recognition. <em>CVPR</em>.</li>
          <li>RME 4221 Introduction to Machine Learning Presentation Assessment Rubric.</li>
        </ul>
      </section>
    </div>
  );
}